version: "2"
services:
    crawler:
        build : .
        ports: 
            - "3003:3003"
        volumes:
            - .:/app/
            - ./node_modules/:/app/node_modules
            - ./image/:/app/image
        command: 
            - /bin/sh
            - -c
            - |
                npm install cheerio --save
                npm install axios --save
                npm install mysql --save
                nodemon index.js
        environment:
            HOST_DB: host.docker.internal
            USER_DB: user
            PASS_DB: test
            SCHEMA_DB: pesantren